// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 the FIawase authors
`ifndef FI_SCAN_CFG_VH
`define FI_SCAN_CFG_VH

// GENERATED by syn/fi_scan_lib.tcl -- do not edit.
// FI_N_FF     encoding bound; only clog2() of it is used, so
//             the FI_Entry field split does not move when L
//             drifts across re-synthesis. Contract: L <= FI_N_FF-1.
// FI_SCAN_LEN measured chain length; informational, the
//             executor uses the runtime CFG_SCAN_LEN (DMI 0x63).

`define FI_N_FF        8192   // -> W_IDX = 13
`define FI_SCAN_LEN    4143

`endif
