// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package i2c_reg_pkg;

  // Address widths within the block
  localparam int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

    typedef struct packed {
      logic        q;
      logic        qe;
    } qstart;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qint_en;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qint_pending;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qmode;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qwrite;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qerror;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qslave_wr;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qslave_rdy;
    typedef struct packed {
      logic [7:0]  q;
      logic        qe;
    } qslave_addr;
    typedef struct packed {
      logic [15:0] q;
      logic        qe;
    } qclk_div;

  typedef struct packed {
    qstart  start;
    qint_en  int_en;
    qint_pending  int_pending;
    qmode  mode;
    qwrite  write;
    qerror  error;
    qslave_wr  slave_wr;
    qslave_rdy  slave_rdy;
    qslave_addr  slave_addr;
    qclk_div  clk_div;
  } i2c_reg2hw_ctrl_reg_t;

    typedef struct packed {
      logic [7:0]  q;
    } qaddress;
    typedef struct packed {
      logic [7:0]  q;
    } qregreg;
    typedef struct packed {
      logic [7:0]  q;
    } qdata;

  typedef struct packed {
      qaddress  address;
      qregreg  regreg;
      qdata  data;
  } i2c_reg2hw_master_data_reg_t;



    typedef struct packed {
      logic [7:0]  q;
    } qaddr0;
    typedef struct packed {
      logic [7:0]  q;
    } qaddr1;
    typedef struct packed {
      logic [7:0]  q;
    } qaddr2;
    typedef struct packed {
      logic [7:0]  q;
    } qaddr3;

  typedef struct packed {
    qaddr0 addr0;
    qaddr1 addr1;
    qaddr2 addr2;
    qaddr3 addr3;
  } i2c_reg2hw_slave_addr_reg_t;

    typedef struct packed {
      logic [7:0]  q;
    } qwdata0;
    typedef struct packed {
      logic [7:0]  q;
    } qwdata1;
    typedef struct packed {
      logic [7:0]  q;
    } qwdata2;
    typedef struct packed {
      logic [7:0]  q;
    } qwdata3;

  typedef struct packed {
     qwdata0 wdata0;
     qwdata1 wdata1;
     qwdata2 wdata2;
     qwdata3 wdata3;
  } i2c_reg2hw_slave_wdata_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } i2c_reg2hw_slave_rdata_reg_t;


    typedef struct packed {
      logic        d;
      logic        de;
    } dstart;
    typedef struct packed {
      logic        d;
      logic        de;
    } dint_en;
    typedef struct packed {
      logic        d;
      logic        de;
    } dint_pending;
    typedef struct packed {
      logic        d;
      logic        de;
    } dmode;
    typedef struct packed {
      logic        d;
      logic        de;
    } dwrite;
    typedef struct packed {
      logic        d;
      logic        de;
    } derror;
    typedef struct packed {
      logic        d;
      logic        de;
    } dslave_wr;
    typedef struct packed {
      logic        d;
      logic        de;
    } dslave_rdy;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dslave_addr;
    typedef struct packed {
      logic [15:0] d;
      logic        de;
    } dclk_div;


  typedef struct packed {
   dstart  start;
   dint_en  int_en;
   dint_pending  int_pending;
   dmode  mode;
   dwrite  write;
   derror  error;
   dslave_wr  slave_wr;
   dslave_rdy  slave_rdy;
   dslave_addr  slave_addr;
   dclk_div  clk_div;
  } i2c_hw2reg_ctrl_reg_t;



    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } daddress;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dregreg;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } ddata;


  typedef struct packed {
    daddress   address;
    dregreg   regreg;
    ddata   data;
  } i2c_hw2reg_master_data_reg_t;


    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } daddr0;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } daddr1;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } daddr2;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } daddr3;


  typedef struct packed {
    daddr0  addr0;
    daddr1  addr1;
    daddr2  addr2;
    daddr3  addr3;
  } i2c_hw2reg_slave_addr_reg_t;


    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dwdata0;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dwdata1;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dwdata2;
    typedef struct packed {
      logic [7:0]  d;
      logic        de;
    } dwdata3;

  typedef struct packed {
    dwdata0 wdata0;
    dwdata1 wdata1;
    dwdata2 wdata2;
    dwdata3 wdata3;
  } i2c_hw2reg_slave_wdata_reg_t;

  // Register -> HW type
  typedef struct packed {
    i2c_reg2hw_ctrl_reg_t ctrl; // [161:120]
    i2c_reg2hw_master_data_reg_t master_data; // [119:96]
    i2c_reg2hw_slave_addr_reg_t slave_addr; // [95:64]
    i2c_reg2hw_slave_wdata_reg_t slave_wdata; // [63:32]
    i2c_reg2hw_slave_rdata_reg_t slave_rdata; // [31:0]
  } i2c_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    i2c_hw2reg_ctrl_reg_t ctrl; // [140:99]
    i2c_hw2reg_master_data_reg_t master_data; // [98:72]
    i2c_hw2reg_slave_addr_reg_t slave_addr; // [71:36]
    i2c_hw2reg_slave_wdata_reg_t slave_wdata; // [35:0]
  } i2c_hw2reg_t;

  // Register offsets
  localparam logic [BlockAw-1:0] I2C_CTRL_OFFSET = 5'h0;
  localparam logic [BlockAw-1:0] I2C_MASTER_DATA_OFFSET = 5'h4;
  localparam logic [BlockAw-1:0] I2C_SLAVE_ADDR_OFFSET = 5'h8;
  localparam logic [BlockAw-1:0] I2C_SLAVE_WDATA_OFFSET = 5'hc;
  localparam logic [BlockAw-1:0] I2C_SLAVE_RDATA_OFFSET = 5'h10;

  // Register index
  typedef enum int {
    I2C_CTRL,
    I2C_MASTER_DATA,
    I2C_SLAVE_ADDR,
    I2C_SLAVE_WDATA,
    I2C_SLAVE_RDATA
  } i2c_id_e;

  // Register width information to check illegal writes
  localparam logic [3:0] I2C_PERMIT [5] = '{
    4'b1111, // index[0] I2C_CTRL
    4'b0111, // index[1] I2C_MASTER_DATA
    4'b1111, // index[2] I2C_SLAVE_ADDR
    4'b1111, // index[3] I2C_SLAVE_WDATA
    4'b1111  // index[4] I2C_SLAVE_RDATA
  };

endpackage

