// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package pinmux_reg_pkg;

  // Address widths within the block
  localparam int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

    typedef struct packed {
      logic [1:0]  q;
    } io0_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io1_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io2_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io3_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io4_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io5_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io6_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io7_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io8_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io9_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io10_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io11_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io12_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io13_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io14_mux;
    typedef struct packed {
      logic [1:0]  q;
    } io15_mux;



  typedef struct packed {
      io0_mux  io0_mux;
      io1_mux  io1_mux;
      io2_mux  io2_mux;
      io3_mux  io3_mux;
      io4_mux  io4_mux;
      io5_mux  io5_mux;
      io6_mux  io6_mux;
      io7_mux  io7_mux;
      io8_mux  io8_mux;
      io9_mux  io9_mux;
      io10_mux  io10_mux;
      io11_mux  io11_mux;
      io12_mux  io12_mux;
      io13_mux  io13_mux;
      io14_mux  io14_mux;
      io15_mux  io15_mux;
  } pinmux_reg2hw_ctrl_reg_t;

  // Register -> HW type
  typedef struct packed {
    pinmux_reg2hw_ctrl_reg_t ctrl; // [31:0]
  } pinmux_reg2hw_t;

  // Register offsets
  localparam logic [BlockAw-1:0] PINMUX_CTRL_OFFSET = 2'h0;

  // Register index
  typedef enum int {
    PINMUX_CTRL
  } pinmux_id_e;

  // Register width information to check illegal writes
  localparam logic [3:0] PINMUX_PERMIT [1] = '{
    4'b1111  // index[0] PINMUX_CTRL
  };

endpackage

