// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package spi_reg_pkg;

  // Address widths within the block
  localparam int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////


  typedef struct packed {
    logic        q;
    logic        qe;
  } qenable;

   typedef struct packed {
      logic        q;
      logic        qe;
    } qint_en;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qint_pending;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qrole_mode;
    typedef struct packed {
      logic [1:0]  q;
      logic        qe;
    } qcp_mode;
    typedef struct packed {
      logic [1:0]  q;
      logic        qe;
    } qspi_mode;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qread;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qmsb_first;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qss_sw_ctrl;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qss_level;
    typedef struct packed {
      logic [3:0]  q;
      logic        qe;
    } qss_delay;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qtx_fifo_reset;
    typedef struct packed {
      logic        q;
      logic        qe;
    } qrx_fifo_reset;
    typedef struct packed {
      logic [2:0]  q;
      logic        qe;
    } qclk_div_pack;



  typedef struct packed {
    qenable       enable;
    qint_en       int_en;
    qint_pending  int_pending;
    qrole_mode    role_mode;
    qcp_mode      cp_mode;
    qspi_mode     spi_mode;
    qread         read;
    qmsb_first    msb_first;
    qss_sw_ctrl   ss_sw_ctrl;
    qss_level     ss_level;
    qss_delay     ss_delay;
    qtx_fifo_reset tx_fifo_reset;
    qrx_fifo_reset rx_fifo_reset;
    qclk_div_pack  clk_div;
  } spi_reg2hw_ctrl0_reg_t;



    typedef struct packed {
      logic        q;
    } qtx_fifo_full;
    typedef struct packed {
      logic        q;
    } qtx_fifo_empty;
    typedef struct packed {
      logic        q;
    } qrx_fifo_full;
    typedef struct packed {
      logic        q;
    } qrx_fifo_empty;
    typedef struct packed {
      logic        q;
    } qbusy;

  typedef struct packed {
   qtx_fifo_full  tx_fifo_full;
   qtx_fifo_empty tx_fifo_empty;
   qrx_fifo_full  rx_fifo_full;
   qrx_fifo_empty rx_fifo_empty;
   qbusy busy;
  } spi_reg2hw_status_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } spi_reg2hw_txdata_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        re;
  } spi_reg2hw_rxdata_reg_t;





    typedef struct packed {
      logic        d;
      logic        de;
    } denable;

   typedef struct packed {
      logic        d;
      logic        de;
   } dint_en;
    typedef struct packed {
      logic        d;
      logic        de;
    } dint_pending;
    typedef struct packed {
      logic        d;
      logic        de;
    } drole_mode;
    typedef struct packed {
      logic [1:0]  d;
      logic        de;
    } dcp_mode;
    typedef struct packed {
      logic [1:0]  d;
      logic        de;
    } dspi_mode;
    typedef struct packed {
      logic        d;
      logic        de;
    } dread;
    typedef struct packed {
      logic        d;
      logic        de;
    } dmsb_first;
    typedef struct packed {
      logic        d;
      logic        de;
    } dss_sw_ctrl;
    typedef struct packed {
      logic        d;
      logic        de;
    } dss_level;
    typedef struct packed {
      logic [3:0]  d;
      logic        de;
    } dss_delay;
    typedef struct packed {
      logic        d;
      logic        de;
    } dtx_fifo_reset;
    typedef struct packed {
      logic        d;
      logic        de;
    } drx_fifo_reset;
    typedef struct packed {
      logic [2:0]  d;
      logic        de;
    } dclk_div_pack;




  typedef struct packed {
    denable       enable;
    dint_en       int_en;
    dint_pending  int_pending;
    drole_mode    role_mode;
    dcp_mode      cp_mode;
    dspi_mode     spi_mode;
    dread         read;
    dmsb_first    msb_first;
    dss_sw_ctrl   ss_sw_ctrl;
    dss_level     ss_level;
    dss_delay     ss_delay;
    dtx_fifo_reset tx_fifo_reset;
    drx_fifo_reset rx_fifo_reset;
    dclk_div_pack  clk_div;
  } spi_hw2reg_ctrl0_reg_t;



    typedef struct packed {
      logic        d;
    } dtx_fifo_full;
    typedef struct packed {
      logic        d;
    } dtx_fifo_empty;
    typedef struct packed {
      logic        d;
    } drx_fifo_full;
    typedef struct packed {
      logic        d;
    } drx_fifo_empty;
    typedef struct packed {
      logic        d;
    } dbusy;


  typedef struct packed {
   dtx_fifo_full  tx_fifo_full;
   dtx_fifo_empty tx_fifo_empty;
   drx_fifo_full  rx_fifo_full;
   drx_fifo_empty rx_fifo_empty;
   dbusy busy;
  } spi_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } spi_hw2reg_rxdata_reg_t;

  // Register -> HW type
  typedef struct packed {
    spi_reg2hw_ctrl0_reg_t ctrl0; // [105:71]
    spi_reg2hw_status_reg_t status; // [70:66]
    spi_reg2hw_txdata_reg_t txdata; // [65:33]
    spi_reg2hw_rxdata_reg_t rxdata; // [32:0]
  } spi_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    spi_hw2reg_ctrl0_reg_t ctrl0; // [71:37]
    spi_hw2reg_status_reg_t status; // [36:32]
    spi_hw2reg_rxdata_reg_t rxdata; // [31:0]
  } spi_hw2reg_t;

  // Register offsets
  localparam logic [BlockAw-1:0] SPI_CTRL0_OFFSET = 4'h0;
  localparam logic [BlockAw-1:0] SPI_STATUS_OFFSET = 4'h4;
  localparam logic [BlockAw-1:0] SPI_TXDATA_OFFSET = 4'h8;
  localparam logic [BlockAw-1:0] SPI_RXDATA_OFFSET = 4'hc;

  // Reset values for hwext registers and their fields
  localparam logic [4:0] SPI_STATUS_RESVAL = 5'h0;
  localparam logic [31:0] SPI_RXDATA_RESVAL = 32'h0;

  // Register index
  typedef enum int {
    SPI_CTRL0,
    SPI_STATUS,
    SPI_TXDATA,
    SPI_RXDATA
  } spi_id_e;

  // Register width information to check illegal writes
  localparam logic [3:0] SPI_PERMIT [4] = '{
    4'b1111, // index[0] SPI_CTRL0
    4'b0001, // index[1] SPI_STATUS
    4'b1111, // index[2] SPI_TXDATA
    4'b1111  // index[3] SPI_RXDATA
  };

endpackage

